# Triggers
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
# Functions
jobs:
    # Build Job
    build:
        # Name of the job
        name: Build Reactjs
        # The OS to run the job on
        runs-on: self-hosted
        # Steps
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version}}
            - run: git pull origin master
            - run: npm i
            - run: npm run build
