name: Deploy

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Copy Repository contents via scp
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.IP }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSH_KEY }}
              with:
                  source: "."
                  target: "/var/www/duan/nestjs-api-ecm"

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.IP }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSH_KEY }}
                  script: ls
